---
name: Python testing

on: pull_request

permissions: read-all

jobs:
  test:
    name: test python code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ">=3.13"

      - name: Install the project
        run: |
          pip install -r test-requirements.txt
          pip install -e .

      - name: Run tests
        run: |
          export KUBECONFIG=$PWD/tests/kubeconf.yaml
          pytest --cov
